---
  java_install_path: /usr/lib/jvm/jre-1.8.0-openjdk

  spark_download_src: http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz
  spark_download_dest: /home/ec2-user/spark-2.1.0-bin-hadoop2.7.tgz
  spark_download_checksum: sha512:3FC94096AE34F9A1A148D37E5ED640A7E5DE1812F1F2ECD715D92BBF2901E895CF4B93E6D8EE0D64DEBB5DF7C56D673C0A36E5FC49503EC0F4507EB0EDF961A4
  spark_extract_dest: /home/ec2-user
  spark_extract_location: /home/ec2-user/spark-2.1.0-bin-hadoop2.7

  scala_download_src: http://downloads.lightbend.com/scala/2.12.1/scala-2.12.1.tgz
  scala_download_dest: /home/ec2-user/scala-2.12.1.tgz
  scala_extract_dest: /home/ec2-user
  scala_extract_location: /home/ec2-user/scala-2.12.1

  host_environment_file: /home/ec2-user/.bashrc

  root_user: ec2-user
