#Create the EC2 Instances Needed for the Cluster
---
  - name: AWS Security Group
    local_action:
      module: 
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_access_secret }}"
      name: "Hadoop"
      description: "Hadoop Cluster Security Group"
      region: "{{ aws_region }}"
      state: present
      rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0

  - name: AWS EC2
    local_action:
      module: ec2
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_access_secret }}"
      region: "{{ aws_region }}"
      group_id: "{{ aws_security_group }}"
      image: "{{ aws_image_master }}"
      instance_type: "{{ aws_instance_type}}"
      exact_count: "{{ count }}"
      count_tag:
        Name: "{{ tag }}"
        ClusterName: "{{ spark_cluster_name }}"
        Environment: "{{ environment_type }}"
        Creator: ansible
      instance_tags: 
        Name: "{{ tag }}"
        ClusterName: "{{ tag_spark_cluster_name }}"
        Environment: "{{ tag_environment_type }}"
        Creator: ansible
      wait: True
    with_items:
      - master_node:
         tag: "hadoop-master"
         count: 1
      #- slave_node:
      #   tag: "hadoop-slave"
      #   count: ""{{  hadoop_slave_count }}""
