---
#Java Installation

  - name: Install Java8
    yum: 
      name: java-1.8.0-openjdk 
      state: latest

  - name: Remove Java7
    yum: 
      name: java-1.7.0-openjdk 
      state: absent

  - name: Set JAVA_HOME
    lineinfile:
      dest: "{{ host_environment_file }}" 
      regexp: "^export JAVA_HOME" 
      line: "export JAVA_HOME={{ java_install_path }}"


#Hadoop Installation

  - name: Download Hadoop
    get_url:
      url: "{{ hadoop_download_src }}"
      dest: "{{ hadoop_download_dest }}"
      checksum: "{{ hadoop_download_checksum }}"

  - name: Extract Hadoop
    unarchive:
      remote_src: yes
      src: "{{ hadoop_download_dest }}" 
      dest: "{{ hadoop_extract_dest }}"

  - name: Set HADOOP_HOME
    lineinfile: 
      dest: "{{ host_environment_file }}"
      state: present
      regexp: "^export HADOOP_HOME"
      line: "export HADOOP_HOME={{ hadoop_install_dir }}"

  #im bad at regexp, refer to this :D
  #http://www.regular-expressions.info/refcharacters.html
  - name: Add Hadoop to Path
    lineinfile: 
      dest: "{{ host_environment_file }}"
      state: present
      regexp: "^export PATH=\$PATH:\$HADOOP_HOME"
      line: "export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin"
  
#Config Files
  - name: Common Configuration
    template:
      src: "{{ item }}.xml"
      dest: "{{ hadoop_install_dir }}/etc/hadoop/{{ item }}.xml"
    with_items: ['core-site', 'hdfs-site', 'mapred-site', 'yarn-site']
