---
  - name: Install Java8
    yum: 
      name: java-1.8.0-openjdk 
      state: latest

  - name: Remove Java7
    yum: 
      name: java-1.7.0-openjdk 
      state: absent

  - name: Set JAVA_HOME
    lineinfile:
      dest: "{{ host_environment_file }}" 
      regexp: "^export JAVA_HOME" 
      line: "export JAVA_HOME={{ java_install_path }}"
